import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, child1, child2
}: {
  children: React.ReactNode,
  child1: React.ReactNode,
  child2: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Parallel Routes</h1>
        <div>
          {child1}
        </div>
        <div>
          {child2}
        </div>
        {children}
      </body>
    </html>
  )
}
